// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFNpqxTPy5NuVTmUtTYy2XpNfwBBE62LY',
    appId: '1:33068603041:web:2f8fbbfcb9a12d4ea702e0',
    messagingSenderId: '33068603041',
    projectId: 'hydro-c8df3',
    authDomain: 'hydro-c8df3.firebaseapp.com',
    storageBucket: 'hydro-c8df3.firebasestorage.app',
    measurementId: 'G-B769B6MFQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc9zkWJJRwD1bYkRg2ct7AEQUPQ6aWouo',
    appId: '1:33068603041:android:7f9d1aa350628ca9a702e0',
    messagingSenderId: '33068603041',
    projectId: 'hydro-c8df3',
    storageBucket: 'hydro-c8df3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAecvpCln8lZ5MLhuswUxAsMXmu0g1plmc',
    appId: '1:33068603041:ios:8ee6c3a9ea35ec81a702e0',
    messagingSenderId: '33068603041',
    projectId: 'hydro-c8df3',
    storageBucket: 'hydro-c8df3.firebasestorage.app',
    iosClientId: '33068603041-iv0dg122re8bgbcn3ers9nd3nfo40hg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.cspProjectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFNpqxTPy5NuVTmUtTYy2XpNfwBBE62LY',
    appId: '1:33068603041:web:074a84f69e66620fa702e0',
    messagingSenderId: '33068603041',
    projectId: 'hydro-c8df3',
    authDomain: 'hydro-c8df3.firebaseapp.com',
    storageBucket: 'hydro-c8df3.firebasestorage.app',
    measurementId: 'G-F600L0V65S',
  );
}
